global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'processor'
    static_configs:
      - targets: ['code_processor:3831']
  - job_name: 'server'
    static_configs:
      - targets: ['server:8000']